[package]
name = "ark-crypto-primitives-macros"
version = "0.4.0"
edition = "2021"

[dependencies]
quote = { version = "1.0" }
syn = { version = "2.0" }
proc-macro2 = { version = "1.0" }

[lib]
proc-macro = true
